services:
  streamcaster-frontend:
    build: ./frontend
    container_name: streamcaster-frontend
    ports:
      - '8080:80'
    depends_on:
      streamcaster-backend:
        condition: service_healthy
    networks:
      - streamcaster-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  streamcaster-backend:
    build: ./backend
    container_name: streamcaster-backend
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - RTMP_SERVER=rtmp://streamcaster-rtmp:1935/live
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - streamcaster-cache:/app/cache
    depends_on:
      streamcaster-rtmp:
        condition: service_healthy
    networks:
      - streamcaster-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  streamcaster-rtmp:
    build: ./rtmp-server
    container_name: streamcaster-rtmp
    environment:
      - BACKEND_HOST=streamcaster-backend:3000
      - CI_MODE=${CI_MODE:-false}
    volumes:
      - streamcaster-data:/opt/rtmp/data
    ports:
      - '1935:1935' # RTMP
      - '8000:8000' # HTTP
    networks:
      - streamcaster-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://127.0.0.1:8000/stat']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  streamcaster-network:

volumes:
  streamcaster-cache:
  streamcaster-data:
