# Production configuration for external RTMP streaming
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  # Remove local RTMP server in production
  rtmp-server:
    profiles:
      - donotstart
  
  # Update receiver for production RTMP
  receiver:
    environment:
      - RTMP_SERVER=${RTMP_SERVER:-rtmp://live.twitch.tv/live}
      - STREAM_KEY=${STREAM_KEY}
    
  # Production resource limits
  controller:
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M