services:
  streamcaster-frontend:
    build: ./frontend
    container_name: streamcaster-frontend
    ports:
      - '8080:80'
    depends_on:
      streamcaster-backend:
        condition: service_healthy
    networks:
      - streamcaster-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  streamcaster-backend:
    build: ./backend
    container_name: streamcaster-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RTMP_SERVER=rtmp://streamcaster-rtmp:1935/live
    volumes:
      - streamcaster-cache:/app/cache
    depends_on:
      streamcaster-rtmp:
        condition: service_healthy
    networks:
      - streamcaster-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  streamcaster-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: streamcaster-rtmp
    volumes:
      - ./rtmp-server/config/nginx.conf:/etc/nginx/nginx.conf
      - streamcaster-data:/opt/rtmp/data
    ports:
      - '1935:1935' # RTMP
      - '8000:8000' # HTTP
    networks:
      - streamcaster-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8000/stat']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  streamcaster-network:

volumes:
  streamcaster-cache:
  streamcaster-data:
