version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - RTMP_SERVER=rtmp://rtmp-server:1935/live
    volumes:
      - media-cache:/app/cache
    depends_on:
      - rtmp-server
    networks:
      - app-network
    restart: unless-stopped

  rtmp-server:
    image: tiangolo/nginx-rtmp
    volumes:
      - ./rtmp-server/config/nginx.conf:/etc/nginx/nginx.conf
      - rtmp-data:/opt/rtmp/data
    ports:
      - "1935:1935"  # RTMP
      - "8000:8000"  # HTTP
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  media-cache:
  rtmp-data: