services:
  rtmp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.rtmp
    container_name: streaming-rtmp-server
    ports:
      - '1935:1935'
      - '8080:8080'
    networks:
      - streaming-network

  ffmpeg-streamer:
    build:
      context: .
      dockerfile: docker/Dockerfile.ffmpeg
    container_name: streaming-ffmpeg
    depends_on:
      - rtmp-server
    volumes:
      - ./playlists:/app/playlists
      - ./scripts:/app/scripts
      - ./videos:/app/videos
    environment:
      - RTMP_URL=rtmp://rtmp-server:1935/live/stream
      - NODE_ENV=development
      - CONTROLLER_MODE=${CONTROLLER_MODE:-dynamic}
    networks:
      - streaming-network
    restart: unless-stopped

networks:
  streaming-network:
    driver: bridge
