version: '3.8'

services:
  rtmp-server:
    image: tiangolo/nginx-rtmp:latest
    container_name: poc-rtmp
    ports:
      - "1935:1935"  # RTMP port (different port to avoid conflict)
      - "8080:80"    # HTTP for stats/admin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
    environment:
      - NGINX_WORKER_PROCESSES=auto
    restart: unless-stopped
    networks:
      - streaming

networks:
  streaming:
    driver: bridge
